### PR TITLE
Fix SSL  Version compatibility Error

### PR DESCRIPTION
**Pull request by kotso**
Fixed error with: cURL error (35): SSL connect error

### CODE REVIEW

**Comment by andrewtch** [comment]
@kotso , what PHP version are you using? Downgrading SSL version is generally a bad idea and using CURLOPT_SSLVERSION is a more general approach.

**Comment by kotso** [comment]
@andrewtch PHP version is 5.6.21 under CentOS 6.7, with all updates installed.

Yes downgrading SSL version is bad idea, just when using CURL_SSLVERSION_DEFAULT somehow curl is unable to detect correct ssl version on server side and comes up with cURL error 35.

Correct solution IMHO will be to have SSLVERSION set to max ssl/tls version that you support now.

But CentOS 6.7 currently shipped with curl 7.19.7 that currently does not support tls1.1, tls1.2 to be set as SSLVERSION (https://curl.haxx.se/libcurl/c/CURLOPT_SSLVERSION.html)

**Comment by andrewtch** [comment]
Ok, my test environment shows curl version as 7.43.0. CentOS is pretty famous with massive delays in package updates, I should say.

Can we possibly fix this by adding Curl options to Client constructor and describe your solution in readme? This will allow users to specify proxies, ssl versions etc.

**Comment by kotso** [comment]
Adding possibility to define curl options like ssl version and proxy support with be great feature :+1:

**Comment by andrewtch** [comment]
@kotso , please check the latest commits - it would allow you to do something like:

```
$client = new Client([CURLOPT_SSLVERSION => CURL_SSLVERSION_TLSv1]);
```

upon client construction. Please check if it fixes your issue!

**Comment by andrewtch** [comment]
Let's assume it is fixed now by curl options (https://github.com/coinfide/php-sdk/blob/master/README.md), you may reopen the PR if needed.

**Pull request closed without merging**
